library(tidyverse)
library(janitor)
library(lubridate)
library(scales)
library(skimr)
library(readr)
ds1<- read_csv("C:/Users/rafiq/Downloads/Downloads/202004-divvy-tripdata.csv")
ds2<- read_csv("C:/Users/rafiq/Downloads/Downloads/202005-divvy-tripdata.csv")
ds3<- read_csv("C:/Users/rafiq/Downloads/Downloads/202006-divvy-tripdata.csv")
ds4<- read_csv("C:/Users/rafiq/Downloads/Downloads/202007-divvy-tripdata.csv")
ds5<- read_csv("C:/Users/rafiq/Downloads/Downloads/202008-divvy-tripdata.csv")
ds6<- read_csv("C:/Users/rafiq/Downloads/Downloads/202009-divvy-tripdata.csv")
ds7<- read_csv("C:/Users/rafiq/Downloads/Downloads/202010-divvy-tripdata.csv")
ds8<- read_csv("C:/Users/rafiq/Downloads/Downloads/202011-divvy-tripdata.csv")
ds9<- read_csv("C:/Users/rafiq/Downloads/Downloads/202012-divvy-tripdata.csv")
ds10<- read_csv("C:/Users/rafiq/Downloads/Downloads/202101-divvy-tripdata.csv")
ds11<- read_csv("C:/Users/rafiq/Downloads/Downloads/202102-divvy-tripdata.csv")
ds12<- read_csv("C:/Users/rafiq/Downloads/Downloads/202103-divvy-tripdata.csv")
all_one<-rbind(ds1,ds2,ds3,ds4,ds5,ds6,ds7,ds8,ds9,ds10,ds11,ds12)
View(all_one)
summary(ds1)
glimpse(ds1)
dim(all_one)
all_one<-janitor::remove_empty(all_one,which =c("cols"))
all_one<-janitor::remove_empty(all_one,which =c("rows"))

all_one$started_at<-lubridate::ymd_hms(all_one$started_at)
all_one$ended_at<-lubridate::ymd_hms(all_one$ended_at)

all_one$start_hour<-lubridate::hour(all_one$started_at)
all_one$end_hour<-lubridate::hour(all_one$ended_at)

all_one$start_date<- as.Date(all_one$started_at)
all_one$end_date<- as.Date(all_one$ended_at)
glimpse(all_one)
View(all_one)
all_one %>% count(start_hour, sort=T) %>%
  ggplot()+geom_line(aes (x=start_hour, y=n),color="red")+ scale_y_continuous(labels = comma)+
  labs(title ="Previous 12 months bike ride by hour", x="Rides start hour", y="Rides count")
all_one$Hours<-difftime(all_one$ended_at, all_one$started_at, units=c ("hours"))
all_one$Minutes<-difftime(all_one$ended_at, all_one$started_at, units=c ("mins"))
fl<-all_one %>% filter(Hours > 0)
glimpse(fl)
dim(all_one)
dim(fl)
fl<- fl %>% select(started_at,ended_at,start_station_name,end_station_name,member_casual,Hours,Minutes)
View(fl)
fl<-fl %>% select(member_casual)
fl<-fl %>% filter(member_casual=="member")
View(fl)
